name: pip3 install dwarf-debugger

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dwarf-debugger
        run: pip3 install dwarf-debugger
